name: Thermals
main: me.ddos.thermals.ThermalsPlugin
version: 0.1
author: DDoS
commands:
   th:
      description: Thermals root command
      usage:
          Invalid arguments, see the Thermals documentation for usage
          
permissions:
  thermals.use: 
    description: use the plugin 
