name: Thermals
main: me.ddos.thermals.ThermalsPlugin
version: 0.1
author: DDoS
commands:
   th:
      description: Thermals root command
      usage: Invalid arguments, see the Thermals documentation for usage

permissions:
  thermals.clear:
    description: Clear heat values
  thermals.get:
    description: Get heat values
  thermals.set:
    description: Set heat values
  thermals.gen:
    description: Generate heat maps
